# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UMC-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UMC-iOS
  pod 'KakaoSDK'

  target 'UMC-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UMC-iOSUITests' do
    # Pods for testing
  end

end
